CREATE DATABASE THUCTAP
GO
USE THUCTAP
GO
CREATE TABLE BRAND(
ID bigint IDENTITY(1,1) primary key ,
BRAND_NAME VARCHAR(100)
)
CREATE TABLE STATUS1(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
STATUS_NAME VARCHAR(100),
)
CREATE TABLE CATEGORY(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
CATE_CODE VARCHAR(20),
CATE_NAME VARCHAR(50)
)
CREATE TABLE SUB_CATEGORY(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
SUB_CATE_CODE VARCHAR(20),
SUB_CATE_NAME VARCHAR(20),
CATE_ID BIGINT,
FOREIGN KEY (CATE_ID) REFERENCES CATEGORY(ID)
)
CREATE TABLE PRODUCT(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
SUBCATE_ID BIGINT,
PRODUCT_NAME VARCHAR(100),
COLOR VARCHAR(50),
QUANTITY BIGINT,
SELL_PRICE DECIMAL(18, 2),
ORIGIN_PRICE DECIMAL(18, 2),
MOTA VARCHAR(MAX),
STATUS_ID BIGINT,
FOREIGN KEY(SUBCATE_ID) REFERENCES SUB_CATEGORY(ID),
FOREIGN KEY(STATUS_ID) REFERENCES STATUS1(ID)
)
CREATE TABLE PRODUCT_BRAND(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_ID BIGINT,
BRAND_ID BIGINT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
)
INSERT INTO BRAND(BRAND_NAME)
VALUES
('Nike'),
('Adidas'),
('Bitis')
INSERT INTO STATUS1(STATUS_NAME)
VALUES
('Con hang'),
('Het hang'),
('Tam ngung ban')

INSERT INTO CATEGORY(CATE_CODE,CATE_NAME)
VALUES
('CATEGORY123','The thao'),
('CATEGORY456','Giay da')
INSERT INTO SUB_CATEGORY(SUB_CATE_CODE,SUB_CATE_NAME,CATE_ID)
VALUES
('SUBCATEGORY123','Da bong',1),
('SUBCATEGORY456','Chay bo',1),
('SUBCATEGORY456','Da bo',2),
('SUBCATEGORY456','Da ca sau',2)
INSERT INTO PRODUCT(SUBCATE_ID,PRODUCT_NAME,COLOR,QUANTITY,SELL_PRICE,ORIGIN_PRICE,MOTA,STATUS_ID)
VALUES
(1,'Giay da bong Nike','Den',20,300000,280000,'Thoai mai',1),
(4,'Giay tay da ca sau','Den',20,300000,280000,'Thoai mai',2)
INSERT INTO PRODUCT_BRAND(PRODUCT_ID,BRAND_ID)
VALUES
(1,1),
(2,2)
Select *from PRODUCT
Select * from BRAND
select * from PRODUCT_BRAND